org.gradle.jvmargs=-Xmx2G

# Fabric Properties (https://fabricmc.net/versions.html)
minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.19.5

# Mod Properties
mod_version=1.0.2
maven_group=kassuk.addon
archives_base_name=blackout

# Dependencies

# Meteor (https://maven.meteordev.org/)
meteor_version=26.2-local
